"""Centralized combat-related constants.

Defines structured log action codes used throughout the combat service.
These codes provide a stable contract for frontend UI logic, accessibility
announcements, analytics, and unit tests without depending on human-readable
message strings.
"""

# Lifecycle / structural
COMBAT_TURN_START = "COMBAT_TURN_START"
ACTOR_START_ACTION = "ACTOR_START_ACTION"
COMBAT_COMPLETE = "COMBAT_COMPLETE"

# Player actions
PLAYER_ATTACK_MISS = "PLAYER_ATTACK_MISS"
PLAYER_ATTACK_HIT = "PLAYER_ATTACK_HIT"
PLAYER_FLEE_SUCCESS = "PLAYER_FLEE_SUCCESS"
PLAYER_FLEE_FAIL = "PLAYER_FLEE_FAIL"
PLAYER_DEFEND = "PLAYER_DEFEND"
PLAYER_USE_ITEM = "PLAYER_USE_ITEM"
PLAYER_SPELL_FIZZLE = "PLAYER_SPELL_FIZZLE"
PLAYER_SPELL_MISS = "PLAYER_SPELL_MISS"
PLAYER_SPELL_HIT = "PLAYER_SPELL_HIT"

# Monster actions
MONSTER_COOLDOWN_WAIT = "MONSTER_COOLDOWN_WAIT"
MONSTER_NO_TARGET_WAIT = "MONSTER_NO_TARGET_WAIT"
MONSTER_INCAPACITATED_WAIT = "MONSTER_INCAPACITATED_WAIT"
MONSTER_SPELL_MISS = "MONSTER_SPELL_MISS"
MONSTER_SPELL_HIT = "MONSTER_SPELL_HIT"
MONSTER_FLEE = "MONSTER_FLEE"
MONSTER_CALL_HELP = "MONSTER_CALL_HELP"
MONSTER_ATTACK_MISS = "MONSTER_ATTACK_MISS"
MONSTER_ATTACK_HIT = "MONSTER_ATTACK_HIT"
MONSTER_HESITATE = "MONSTER_HESITATE"

# Groupings (useful for tests / UI classification)
PLAYER_CODES = {
    PLAYER_ATTACK_MISS,
    PLAYER_ATTACK_HIT,
    PLAYER_FLEE_SUCCESS,
    PLAYER_FLEE_FAIL,
    PLAYER_DEFEND,
    PLAYER_USE_ITEM,
    PLAYER_SPELL_FIZZLE,
    PLAYER_SPELL_MISS,
    PLAYER_SPELL_HIT,
}

MONSTER_CODES = {
    MONSTER_COOLDOWN_WAIT,
    MONSTER_NO_TARGET_WAIT,
    MONSTER_INCAPACITATED_WAIT,
    MONSTER_SPELL_MISS,
    MONSTER_SPELL_HIT,
    MONSTER_FLEE,
    MONSTER_CALL_HELP,
    MONSTER_ATTACK_MISS,
    MONSTER_ATTACK_HIT,
    MONSTER_HESITATE,
}

LIFECYCLE_CODES = {COMBAT_TURN_START, ACTOR_START_ACTION, COMBAT_COMPLETE}

ALL_CODES = PLAYER_CODES | MONSTER_CODES | LIFECYCLE_CODES
