# Ruff configuration
line-length = 100
exclude = [
  ".venv",
  "app/static/iconography",
  "app/static/*.svg"
]
select = ["E", "F", "W", "I"]  # pycodestyle, pyflakes, warnings, isort
ignore = [
  # Add rule codes here to ignore specific cases
]
